### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by CHJ85** [zoltanp/xrandr-invert-colors#23] opened 2021-01-02 16:07 UTC
The "make" command spits out an error:
```
cc -Wall -Wextra -O0 -ggdb -std=c99 -c gamma_randr.c
gamma_randr.c:39:10: fatal error: xcb/randr.h: No such file or directory
   39 | #include <xcb/randr.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:10: xrandr-invert-colors.bin] Error 1

```

**Comment by Tinram** [comment] 2021-01-03 16:43
I confirm the error upon attempting to execute make.

Comparing the current code with the last version I downloaded (Sep 2019), the _make_ file appears to be for development: **-O0 -ggdb** (instead of no GDB switch and -O3 optimization).

**Comment by koo5** [comment] 2021-01-03 21:13
` -O0 -ggdb ` shouldn't cause this. Make sure you followed https://github.com/zoltanp/xrandr-invert-colors#dependencies

**Comment by Tinram** [comment] 2021-01-03 21:17
That's right, those switches won't be the cause of the problem.  Yet the make file has changed compared to the older 2019 one, and those switches indicate a development state.  I was wondering whether the make file really was the intended production one.

**Comment by koo5** [comment] 2021-01-04 03:12
ok. master branch builds fine for me:
```
koom@dev ~/repos> git clone git@github.com:zoltanp/xrandr-invert-colors.git
Cloning into 'xrandr-invert-colors'...
remote: Enumerating objects: 84, done.
remote: Total 84 (delta 0), reused 0 (delta 0), pack-reused 84
Receiving objects: 100% (84/84), 19.80 KiB | 285.00 KiB/s, done.
Resolving deltas: 100% (41/41), done.
koom@dev ~/repos> cd xrandr-invert-colors/
koom@dev ~/repos/xrandr-invert-colors (master)> make
c99 -Wall -Wextra -O0 -ggdb -std=c99   -c -o gamma_randr.o gamma_randr.c
c99 -Wall -Wextra -O0 -ggdb -std=c99   -c -o xrandr-invert-colors.o xrandr-invert-colors.c
c99  -o xrandr-invert-colors gamma_randr.o xrandr-invert-colors.o -lxcb-randr -lxcb
koom@dev ~/repos/xrandr-invert-colors (master)> 
```

**Comment by zoltanp** [comment] 2021-01-04 11:45
@CHJ85 

> gamma_randr.c:39:10: fatal error: xcb/randr.h: No such file or directory

Have you installed the xrandr development packages/files ? `libxcb-randr0-dev` on Debian, Ubuntu.

The error looks like the development files (headers) are not found.

**Comment by zoltanp** [comment] 2021-01-04 11:53
@Tinram 

>  I was wondering whether the make file really was the intended production one.

You are right that disabling optimisations and enabling debug info is atypical for production use, probably it's pointless.
Still, for a 34 KiB executable which includes debug info, I haven't bothered to change the flags or have a separate production build. The application's algorithmic complexity is practically constant, anyway.

**Comment by CHJ85** [comment] 2021-01-04 13:05
@zoltanp Thank you so much. That is totally what it was.
And now I feel stupid for not seeing that under Dependencies. 😀
Sorry for wasting your time, guys.

**Comment by zoltanp** [comment] 2021-01-05 08:14
Nice to hear that it works now!

I'm closing this issue.

**Closed as completed by zoltanp** 2021-01-05 08:14 UTC
